spring:
  datasource:
    # localhost 주소를 지우고, 구글 Secret Manager 금고에서 주입되는 환경변수들을 조합한 구글 전용 주소로 바꿉니다!
    url: jdbc:mysql:///${DB_NAME}?cloudSqlInstance=${DB_HOST}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 70643aa944aee3a7b8696475602ed3f08d475dc76de6c8e081af3819e4e85f2b

ai:
  api:
    key: ${GEMINI_API_KEY}